const pathnames = {
  publics: {
    homepage: "",
    layout: "",
    login: "dang-nhap",
    chothuecanho: "cho-thue-can-ho",
    nhachothue: "nha-cho-thue",
    chothuephongtro: "cho-thue-phong-tro",
    search: "tim-kiem",
    detailPost_idPost: "chi-tiet-tin-dang/:idPost",
    detailPost: "chi-tiet-tin-dang/",
    news: "tin-tuc",
    detailNews__id: "chi-tiet-tin-tuc/:id",
    detailNews: "chi-tiet-tin-tuc/",
    payment__status: "thanh-toan/:code",
    resetPassword: "Reset-mat-khau",
    updatePassword: "cap-nhat-mat-khau",
  },
  user: {
    layout: "thanh-vien/",
    personal: "ca-nhan",
    changeEmail: "cap-nhat-email",
    changePhone: "cap-nhat-so-dien-thoai",
    wishlist: "tin-dang-yeu-thich",
    seenPost: "tin-dang-da-xem",
    deposit: "nap-tien",
    depositVnpay: "nap-tien-vnpay",
    paymentHistory: "lich-su-nap-tien",
    expiredHistory: "lich-su-gia-han",
    balanceInfo: "thong-tin-so-du",
  },
  owner: {
    general: "tong-quan",
    createPost: "tao-moi-tin-dang",
    managePost: "quan-ly-tin-dang",
    layout: "chu-tro/",
    manageOrder: "quan-ly-hoa-don",
  },
  paymentOnBoarding: "/thanh-toan-paypal",
  admin: {
    general: "tong-quan",
    manageUser: "quan-ly-thanh-vien",
    layout: "admin/",
    createNews: "tao-moi-tin-tuc",
    manageNews: "quan-ly-tin-tuc",
    manageOrder: "quan-ly-hoa-don",
  },
}

export default pathnames
