const Joi = require("joi")

exports.string = Joi.string().allow(null, "")
exports.stringReq = Joi.string().required()
exports.numberReq = Joi.number().required()
exports.dateReq = Joi.date().required()
exports.date = Joi.date().allow(null, "")
exports.number = Joi.number().allow(null, "")
exports.array = Joi.array().allow(null, "")
exports.arrayReq = Joi.array().required()
exports.boolean = Joi.boolean().allow(null, "")
exports.emailReq = Joi.string()
  .required()
  .email({ minDomainSegments: 2, tlds: { allow: ["com", "net"] } })
